<div align="center">
    <img src="images/zb-logo.png" alt="제로베이스" width="100%">
    <br>
    <a href="https://zerobaseschool.notion.site/DS-EDA-Lv-Test-b7d5e895c7cd4dda813c8fe2f2c23f79"><img src="images/openinnotion_logo.png" alt="EDA Lv Test Doc" width="12%"></a>

이 Jupyter Notebook 파일은 <a href="https://zero-base.co.kr/category_data_camp/school_DS">제로베이스</a>에서 제공하는 **EDA Level Test** 문제입니다.<br>
지금까지 공부하신 내용으로 데이터 분석에 대해 좀 더 연습할 수 있는 시간이 되셨으면 좋겠습니다.🙂<br>
**EDA Level Test**에 대한 안내 사항은 상단 **Open in ZeroBase Notion** 로고를 클릭하여 확인해주세요!<br>
반드시 시작 전에 내용을 숙지해주시기를 바랍니다!<br>
</div>

***

<h1 style="background-color:#9F81F7;color:#D8D8D8;font-weight:bold;display:inline-block;padding: 5px">EDA Level Test 03 ⭐️⭐️</h1>

| Week | Data Analysis | Difficulty | This Notebook |
|------|---------------|------------|-------|
| 1    | 서울시 인구 데이터 | ⭐️ ||
| 2    | 화장품 성분 데이터 | ⭐️⭐️⭐️ ||
| 3    | 올림픽 데이터 | ⭐️⭐️ |👈|
| 4    | 국가별 인터넷 사용률 데이터 |⭐️⭐️ ||
| 5    | 전국 박물관/미술관 정보 표준 데이터 | ⭐️⭐️⭐️ ||
| 6    | 서울시 흡연율 통계 데이터 | ⭐️⭐️ ||
| 7    | 웹크롤링 | ⭐️ ||
| 8    | 서울시 지하철 호선별 역별 유/무임 승하차 인원 정보 데이터 | ⭐️⭐️ ||
| 9    | 서울시 교통사고 현황 (사고유형별) 통계 데이터 | ⭐️⭐️ ||
| 10   | 서울시 교통사고 현황 (사고유형별) 통계 + 서울시 차량통행속도 (구별/월별) 통계 + 서울시 인구밀도 (구별) 통계 | ⭐️⭐️⭐️ ||

## 문제 소개 및 데이터 준비 단계

<div style="border: 1px solid black; padding: 10px;">

- 총 2단계 데이터 분석 상황 제시
    - 총점 100점
<br></br>
- 1단계 DataFrame 불러오기 & 전처리
- 2단계 DataFrame 가공하기

### Data 원본 출처

##### Target Data(CSV): 역대(1976-2008) 하계 올림픽 메달리스트에 대한 정보
- Source: [Kaggle](https://www.kaggle.com/datasets/divyansh22/summer-olympics-medals)
- DownLoad: [archive.zip](https://www.kaggle.com/datasets/divyansh22/summer-olympics-medals/download)

##### 참고사항: **해당 데이터 분석시 한계점**
- 해당 데이터는 공식 데이터([국제스포츠정보센터](https://gsic.sports.or.kr/com/cop/game/game_info.do?partCode=1))와 차이가 있음.
    - 대한민국 데이터 누락예시: 2008년 베이징올림픽 역도 48kg 은메달 임정화 누락
<br></br>
- 복식/단체 종목의 경우 한 종목에서 여러명이 메달을 획득하지만, 국가 순위 집계시 1개로 집계됨
    - 동일 종목인 경우 1개로 계산하는 것이 용이
<br></br>
    - 단, 3,4위 모두에 동메달을 주는 경우 한 나라에서 동메달 2개 획득시 문제 발생
        - 대한민국 사례: 1992년 바르셀로나 올림픽 실제 탁구 남성복식 2팀 준결승 진출로 및 패배로 동메달 2개 획득
            - 당시 준결승 진출시 동메달 수여, 총 4명
            - -> 이 자료에서는 누가 누구와 복식조를 이뤘는지 구분할 수 없으며 동일종목이므로 이 자료로 국가 순위 집계시 문제 발생
            - 참고: 현재 올림픽 탁구 복식 4위에게는 동메달을 수여하지 않음
<br></br>
- 올림픽 메달 취소 등 반영 안되어있음
<br></br>
- 복식/단체 종목의 선수 수, 당시 메달 수여 룰, 메달 취소 및 승격/승계 등의 실제 메타데이터가 없이는 확인 어려움
<br></br>
-  **이러한 이유로 해당 자료 자체만으로 Test 진행 할 예정이며, 국가별 메달 집계시 동일종목당 1개의 메달로 계산**

</div>

## 문제 시작! 🏃🏻

## 1단계: Load Data & Preprocessing
***

### 3-1. Load Target Data

### 문제 1-1) Target Data 가져오기 (10점)
- 위에 제시된 링크 혹은 datas 폴더에 있는 데이터(Summer-Olympic-medals-1976-to-2008.csv)를 Pandas DataFrame으로 읽어 오세요.
<br></br>
    - 참고: 아래와 같이 읽어올 경우 에러가 발생합니다.
<br></br>
    <img src="images/03-1-1-001.png" style="margin:auto" width=800/>
<br></br>
    - hint1: 에러 메시지를 확인하세요.
<br></br>
    - hint2: 해당 데이터는 영어로 이루어져 있습니다.
<br></br>
- 완료 후 결과 dataframe 변수를 check_01_01 함수에 입력하여 채점하세요.

In [1]:
# 1-1
import pandas as pd
import copy
# 채점을 위한 코드입니다. 반드시 실행해주세요.
from grading import *

df_target = pd.read_csv('../source_code/datas-20240219T072537Z-001/datas/Summer-Olympic-medals-1976-to-2008.csv', encoding='unicode_escape' )
check_01_01(df_target)
df_target

정답입니다! 10점 누적 되었습니다!
현재 누적 점수: 10 / 100

,City,Year,Sport,Discipline,Event,Athlete,Gender,Country_Code,Country,Event_gender,Medal
0,Montreal,1976.0,Aquatics,Diving,3m springboard,"KÖHLER, Christa",Women,GDR,East Germany,W,Silver
1,Montreal,1976.0,Aquatics,Diving,3m springboard,"KOSENKOV, Aleksandr",Men,URS,Soviet Union,M,Bronze
2,Montreal,1976.0,Aquatics,Diving,3m springboard,"BOGGS, Philip George",Men,USA,United States,M,Gold
3,Montreal,1976.0,Aquatics,Diving,3m springboard,"CAGNOTTO, Giorgio Franco",Men,ITA,Italy,M,Silver
4,Montreal,1976.0,Aquatics,Diving,10m platform,"WILSON, Deborah Keplar",Women,USA,United States,W,Bronze
...,...,...,...,...,...,...,...,...,...,...,...
15428,Beijing,2008.0,Wrestling,Wrestling Gre-R,66 - 74kg,"GUENOT, Christophe",Men,FRA,France,M,Bronze
15429,Beijing,2008.0,Wrestling,Wrestling Gre-R,66 - 74kg,"KVIRKELIA, Manuchar",Men,GEO,Georgia,M,Gold
15430,Beijing,2008.0,Wrestling,Wrestling Gre-R,55 - 60kg,"RAHIMOV, Vitaliy",Men,AZE,Azerbaijan,M,Silver
15431,Beijing,2008.0,Wrestling,Wrestling Gre-R,60 - 66kg,"GUENOT, Steeve",Men,FRA,France,M,Gold
15432,Beijing,2008.0,Wrestling,Wrestling Gre-R,96 - 120kg,"LOPEZ, Mijain",Men,CUB,Cuba,M,Gold

In [2]:
df_target

,City,Year,Sport,Discipline,Event,Athlete,Gender,Country_Code,Country,Event_gender,Medal
0,Montreal,1976.0,Aquatics,Diving,3m springboard,"KÖHLER, Christa",Women,GDR,East Germany,W,Silver
1,Montreal,1976.0,Aquatics,Diving,3m springboard,"KOSENKOV, Aleksandr",Men,URS,Soviet Union,M,Bronze
2,Montreal,1976.0,Aquatics,Diving,3m springboard,"BOGGS, Philip George",Men,USA,United States,M,Gold
3,Montreal,1976.0,Aquatics,Diving,3m springboard,"CAGNOTTO, Giorgio Franco",Men,ITA,Italy,M,Silver
4,Montreal,1976.0,Aquatics,Diving,10m platform,"WILSON, Deborah Keplar",Women,USA,United States,W,Bronze
...,...,...,...,...,...,...,...,...,...,...,...
15428,Beijing,2008.0,Wrestling,Wrestling Gre-R,66 - 74kg,"GUENOT, Christophe",Men,FRA,France,M,Bronze
15429,Beijing,2008.0,Wrestling,Wrestling Gre-R,66 - 74kg,"KVIRKELIA, Manuchar",Men,GEO,Georgia,M,Gold
15430,Beijing,2008.0,Wrestling,Wrestling Gre-R,55 - 60kg,"RAHIMOV, Vitaliy",Men,AZE,Azerbaijan,M,Silver
15431,Beijing,2008.0,Wrestling,Wrestling Gre-R,60 - 66kg,"GUENOT, Steeve",Men,FRA,France,M,Gold
15432,Beijing,2008.0,Wrestling,Wrestling Gre-R,96 - 120kg,"LOPEZ, Mijain",Men,CUB,Cuba,M,Gold

### 문제 1-2) Preprocessing: missing data 처리 (10점)
- 1-1에서 읽은 Data에는 missing data가 있습니다. missing data를 확인하고 처리하세요.
<br></br>
    - 조건1: missing data가 있다면, 해당 row(행)를 삭제(drop)하세요
    - 조건2: Index를 초기화(reset)하고, 기존 Index는 삭제(drop)하세요.
<br></br>
- 완료 후 결과 dataframe 변수를 check_01_02 함수에 입력하여 채점하세요.

In [3]:
# 1-2
df_target.dropna(axis=0, inplace=True)
df_target.reset_index(drop=True, inplace=True)
check_01_02(df_target)

정답입니다! 10점 누적 되었습니다!
현재 누적 점수: 20 / 100

In [4]:
df_target

,City,Year,Sport,Discipline,Event,Athlete,Gender,Country_Code,Country,Event_gender,Medal
0,Montreal,1976.0,Aquatics,Diving,3m springboard,"KÖHLER, Christa",Women,GDR,East Germany,W,Silver
1,Montreal,1976.0,Aquatics,Diving,3m springboard,"KOSENKOV, Aleksandr",Men,URS,Soviet Union,M,Bronze
2,Montreal,1976.0,Aquatics,Diving,3m springboard,"BOGGS, Philip George",Men,USA,United States,M,Gold
3,Montreal,1976.0,Aquatics,Diving,3m springboard,"CAGNOTTO, Giorgio Franco",Men,ITA,Italy,M,Silver
4,Montreal,1976.0,Aquatics,Diving,10m platform,"WILSON, Deborah Keplar",Women,USA,United States,W,Bronze
...,...,...,...,...,...,...,...,...,...,...,...
15311,Beijing,2008.0,Wrestling,Wrestling Gre-R,66 - 74kg,"GUENOT, Christophe",Men,FRA,France,M,Bronze
15312,Beijing,2008.0,Wrestling,Wrestling Gre-R,66 - 74kg,"KVIRKELIA, Manuchar",Men,GEO,Georgia,M,Gold
15313,Beijing,2008.0,Wrestling,Wrestling Gre-R,55 - 60kg,"RAHIMOV, Vitaliy",Men,AZE,Azerbaijan,M,Silver
15314,Beijing,2008.0,Wrestling,Wrestling Gre-R,60 - 66kg,"GUENOT, Steeve",Men,FRA,France,M,Gold
15315,Beijing,2008.0,Wrestling,Wrestling Gre-R,96 - 120kg,"LOPEZ, Mijain",Men,CUB,Cuba,M,Gold

### 문제 1-3) Preprocessing: Data Type 정리 (10점)
- 1-2에서 만든 DataFrame을 아래의 조건에 따라 데이터의 타입을 확인하고 변경해주세요.
<br></br>
    - 조건1: float data는 int로 변경해주세요.
    - 조건2: float data외의 모든 데이터가 string 인지 확인해주세요.
<br></br>
- 완료 후 결과 dataframe 변수를 check_01_03 함수에 입력하여 채점하세요.

In [5]:
# 1-3
df_target.dtypes
df_target['Year'] = df_target['Year'].astype('int')
check_01_03(df_target)

정답입니다! 10점 누적 되었습니다!
현재 누적 점수: 30 / 100

In [6]:
# 나머지 데이터는 처음부터 string
df_target.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15316 entries, 0 to 15315
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   City          15316 non-null  object
 1   Year          15316 non-null  int32
 2   Sport         15316 non-null  object
 3   Discipline    15316 non-null  object
 4   Event         15316 non-null  object
 5   Athlete       15316 non-null  object
 6   Gender        15316 non-null  object
 7   Country_Code  15316 non-null  object
 8   Country       15316 non-null  object
 9   Event_gender  15316 non-null  object
 10  Medal         15316 non-null  object
dtypes: int32(1), object(10)
memory usage: 1.2+ MB

## 2단계: 원하는 Data로 가공하기
***

### 문제 2-1) 2008년 대한민국 메달리스트 찾기 (15점)
- 문제 1에서 만든 DataFrame을 이용하여 2008년 베이징 올림픽 양궁 종목에서 금메달을 획득한 선수들을 찾아보세요.
<br></br>
    - 조건1: 2008년 베이징 올림픽 양궁 종목의 금메달리스트만 있는 DataFrame을 만들어 주세요
        - 예시: 1992년 바르셀로나 올림픽 양궁 금메달리스트 DataFrame
        <img src="images/03-2-1-001.png" style="margin:auto" width=800/>
    - 참고: 추후 문제풀이시 문제 없게 하기 위해서 현재데이터를 deep copy하여 진행하시는 것을 추천드립니다.
        - 하지 않아도 문제는 없으나 코드 작성 방법에 따라 다음 문제 풀이시 다시 load하고 전처리 진행해야 할 수도 있습니다.
<br></br>
- 완료 후 결과 dataframe 변수를 check_02_01 함수에 입력하여 채점하세요.

In [7]:
# 2-1
df_archery = df_target.copy()
df_archery = df_archery[(df_archery['City'] == 'Beijing')&(df_archery['Discipline']=='Archery')&(df_archery['Medal']=='Gold')&(df_archery['Country_Code']=='KOR')]
df_archery
check_02_01(df_archery)

정답입니다! 15점 누적 되었습니다!
현재 누적 점수: 45 / 100

In [8]:
df_archery

,City,Year,Sport,Discipline,Event,Athlete,Gender,Country_Code,Country,Event_gender,Medal
13622,Beijing,2008,Archery,Archery,team (FITA Olympic round - 70m),"YUN, Ok-Hee",Women,KOR,"Korea, South",W,Gold
13636,Beijing,2008,Archery,Archery,team (FITA Olympic round - 70m),"JOO, Hyun-Jung",Women,KOR,"Korea, South",W,Gold
13637,Beijing,2008,Archery,Archery,team (FITA Olympic round - 70m),"LEE, Chang-Hwan",Men,KOR,"Korea, South",M,Gold
13639,Beijing,2008,Archery,Archery,team (FITA Olympic round - 70m),"IM, Dong-Hyun",Men,KOR,"Korea, South",M,Gold
13640,Beijing,2008,Archery,Archery,team (FITA Olympic round - 70m),"PARK, Kyung-Mo",Men,KOR,"Korea, South",M,Gold
13644,Beijing,2008,Archery,Archery,team (FITA Olympic round - 70m),"PARK, Sung-Hyun",Women,KOR,"Korea, South",W,Gold

### 문제 2-2) 대한민국 역대(1976-2008) 하계 올림픽 메달 획득 내역 확인(15점)
- 문제 1에서 만든 DataFrame과 Pandas 기능을 활용하여 아래 예시와 같은 형태의 대한민국 역대 메달 획득 내역을 만들어주세요.
<br></br>
    - 조건1: Index는 Year - Medal로 보여주세요(아래 예시 참고)
<br></br>
    - 조건2: Index에서 Year는 내림차순, Medal은 Gold-Silver-Bronze 순으로 보여주세요(아래 예시 참고)
<br></br>
        - 예시: 미국의 역대 메달 획득 내역
<br></br>
        <img src="images/03-2-2-001.png" style="margin:right" width=150/>
<br></br>
<br></br>
    - hint1: 앞서 이야기 한 바와 같이, 메달 숫자는 복식/단체 종목을 감안하여 선수명(Athlete)과 성별(Gender)를 제외한 내용이 일치할 경우 같은 경기에서 획득한 메달로 간주하시면 됩니다.
<br></br>
    - hint2: 내용이 일치하는 데이터를 삭제하기 위한 방법은 drop_duplicate, groupby, pivot_table 등 다양한 방법이 있습니다.
<br></br>
    - hint3: Medal Index의 정렬 순서를 'Gold'-'Silver'-'Bronze'로 하기 위해서 sort_index의 'key' argument에 dictionary를 활용할 수 있습니다.
        - 이 외에 sort_index의 다른 arguments도 확인해 보세요
<br></br>
<br></br>
    - 참고1: 예시와 같이 컬럼명은 City 등 아무 컬럼명이든 상관 없습니다. 하나의 컬럼만 보여주세요.
<br></br>
    - 참고2: 추후 문제풀이시 문제 없게 하기 위해서 현재데이터를 deep copy하여 진행하시는 것을 추천드립니다.
        - 하지 않아도 문제는 없으나 코드 작성 방법에 따라 다음 문제 풀이시 다시 load하고 전처리 진행해야 할 수도 있습니다.
<br></br>
    - 참고3: 대한민국은 1980년 모스크바 올림픽에 참가하지 않았습니다.
<br></br>
- 완료 후 결과 dataframe 변수를 check_02_02 함수에 입력하여 채점하세요.

In [9]:
# 2-2
df_target_copy = df_target.copy()
df_target_copy = df_target_copy[df_target_copy['Country']=='Korea, South']
df_target_copy.drop_duplicates(subset=['City','Year','Sport','Discipline','Event','Country_Code','Country','Medal','Event_gender'], ignore_index=True, keep='first', inplace=True)
df_target_copy['City'] = 1
medal_order = {'Gold':0, 'Silver':1, 'Bronze':2}
df_kor = pd.pivot_table(df_target_copy, index=['Year','Medal'], values='City', aggfunc='sum').sort_index(level = 1, key = lambda x : x.map(medal_order), sort_remaining = False).sort_index(level = 0, ascending=True, sort_remaining = False)
check_02_02(df_kor)

정답입니다! 15점 누적 되었습니다!
현재 누적 점수: 60 / 100

C:\Users\diana\OneDrive\문서\ds_study\source_code\grading.py:98: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  condition03 = df.loc[(2008,'Gold')][0] == 13
C:\Users\diana\OneDrive\문서\ds_study\source_code\grading.py:99: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  condition04 = df.loc[(1976,'Bronze')][0] == 4

In [10]:
df_kor

             City
Year Medal
1976 Gold       1
     Silver     1
     Bronze     4
1984 Gold       6
     Silver     6
     Bronze     7
1988 Gold      12
     Silver    10
     Bronze    11
1992 Gold      12
     Silver     5
     Bronze    11
1996 Gold       7
     Silver    15
     Bronze     5
2000 Gold       8
     Silver    10
     Bronze    10
2004 Gold       9
     Silver    12
     Bronze     9
2008 Gold      13
     Silver    10
     Bronze     8

### 문제 2-3) 1996년 애틀란타 올림픽 총 메달 개수 기준 상위 10개 국가 확인하기(20점)
- 문제 1에서 만든 DataFrame과 Pandas 기능을 활용하여 아래 예시와 같은 형태의 **총** 메달 개수 기준 상위 10개국 내역을 만들어주세요.
<br></br>
    - 조건1: Index는 앞선 1단계에서 Preprocessing한 Data의 Index 그대로 나두어 주세요.
<br></br>
    - 조건2: 총 메달 개수로 오름차순 정렬 후 상위 10개 국가만 나타내는 DataFrame을 만드세요.
<br></br>
    - 조건3: 결과 DataFrame의 Columns은 ['Country', 'Medal'] 입니다.
<br></br>
        - 예시: 1992년 바르셀로나 올림픽 총 메달 개수에 따른 상위 10개 국가
<br></br>
        <img src="images/03-2-3-001.png" style="margin:right" width=200/>
<br></br>
<br></br>
    - hint1: 앞서 이야기 한 바와 같이, 메달 숫자는 복식/단체 종목을 감안하여 선수명(Athlete)과 성별(Gender)를 제외한 내용이 일치할 경우 같은 경기에서 획득한 메달로 간주하시면 됩니다.
<br></br>
    - hint2: 내용이 일치하는 데이터를 삭제하기 위한 방법은 drop_duplicate, groupby, pivot_table 등 다양한 방법이 있습니다.
<br></br>
    - hint3: Groupby, Pivot_table 등의 기능을 활용하는 경우 'as_index' 혹은 'index'와 같은 argument를 활용하세요
<br></br>
<br></br>
    - 참고: 추후 문제풀이시 문제 없게 하기 위해서 현재데이터를 deep copy하여 진행하시는 것을 추천드립니다.
        - 하지 않아도 문제는 없으나 코드 작성 방법에 따라 다음 문제 풀이시 다시 load하고 전처리 진행해야 할 수도 있습니다.
<br></br>
- 완료 후 결과 dataframe 변수를 check_02_03 함수에 입력하여 채점하세요.

In [11]:
# 2-3
df_rank_copy = df_target.copy()
df_rank_copy = df_rank_copy[df_rank_copy['City'] == 'Atlanta']
df_rank_copy.drop_duplicates(subset=['City','Year','Sport','Discipline','Event','Country_Code','Country','Medal','Event_gender'], ignore_index=True, keep='first', inplace=True)
df_rank_10 = df_rank_copy.groupby(['Country'], as_index=False)['Medal'].count()
df_rank_10.sort_values(by='Medal', ascending=False, axis=0, inplace=True)
df_rank_10 = df_rank_10.nlargest(10, 'Medal', keep='last')
df_rank_10
check_02_03(df_rank_10)

정답입니다! 20점 누적 되었습니다!
현재 누적 점수: 80 / 100

C:\Users\diana\OneDrive\문서\ds_study\source_code\grading.py:114: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  condition01 = df.iloc[3][0] == 'China'
C:\Users\diana\OneDrive\문서\ds_study\source_code\grading.py:115: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  condition02 = df.iloc[3][1] == 50
C:\Users\diana\OneDrive\문서\ds_study\source_code\grading.py:117: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  condition04 = df.iloc[-1][0] == 'Ukraine'

In [12]:
df_rank_10.count()

Country    10
Medal      10
dtype: int64

In [13]:
df_rank_10

          Country  Medal
75  United States    101
24        Germany     65
58         Russia     63
13          China     50
3       Australia     41
22         France     37
33          Italy     35
39   Korea, South     27
16           Cuba     25
73        Ukraine     23

### 문제 2-4) 1996년 애틀란타 올림픽 금매달 개수 기준 상위 10개 국가 확인하기(20점)
- 문제 1에서 만든 DataFrame과 Pandas 기능을 활용하여 아래 예시와 같은 형태의 **금**메달 개수 기준 상위 10개국 내역을 만들어주세요.
<br></br>
    - 조건1: 'Gold', 'Silver', 'Bronze' 컬럼을 만들고, 해당 Row(행)의 Medal 이 Gold면 'Gold' 컬럼에 1, Silver면 'Silver' 컬럼에 1, 'Bronze'면 'Bronze'컬럼에 1을 입력하세요
        - 추후 아래 예시와 같은 형태로 DataFrame을 만들기 위한 작업입니다. 적당한 순서에 맞추어 해당 작업을 하시면 되고, 혹시 이 작업이 필요 없을 경우 안하셔도 무방합니다.
<br></br>
    - 조건2: Index는 앞선 1단계에서 Preprocessing한 Data의 Index 그대로 나두어 주세요.
<br></br>
    - 조건3: 금메달 개수로 내림차순 정렬 후 상위 10개 국가만 나타내는 DataFrame을 만드세요.
        - 만약 금메달 개수가 같다면, 은메달 개수가 많은 국가가 더 높은 순위이며 은메달 개수도 같다면 동메달 개수가 더 많은 국가가 상위입니다.
<br></br>
    - 조건4: 결과 DataFrame의 Columns은 ['Country', 'Gold', 'Silver', 'Bronze'] 입니다.
<br></br>
        - 예시: 1992년 바르셀로나 올림픽 총 메달 개수에 따른 상위 10개 국가
<br></br>
        <img src="images/03-2-4-001.png" style="margin:right" width=300/>
<br></br>
<br></br>
    - hint1: 앞서 이야기 한 바와 같이, 메달 숫자는 복식/단체 종목을 감안하여 선수명(Athlete)과 성별(Gender)를 제외한 내용이 일치할 경우 같은 경기에서 획득한 메달로 간주하시면 됩니다.
<br></br>
    - hint2: 내용이 일치하는 데이터를 삭제하기 위한 방법은 drop_duplicate, groupby, pivot_table 등 다양한 방법이 있습니다.
<br></br>
    - hint3: Groupby, Pivot_table 등의 기능을 활용하는 경우 'as_index' 혹은 'index'와 같은 argument를 활용하세요
<br></br>
<br></br>
- 완료 후 결과 dataframe 변수를 check_02_04 함수에 입력하여 채점하세요.

In [61]:
# 2-4
import numpy as np
#반복문으로 gold, silver, bronze 컬럼에 1추가
df_rank_copy = df_target.copy()
df_rank_copy = df_rank_copy[df_rank_copy['City']=='Atlanta']
df_rank_copy.drop_duplicates(subset=['City','Year','Sport','Discipline','Event','Country_Code','Country','Medal','Event_gender'], ignore_index=True, keep='first',inplace=True)
df_rank_copy['Gold'] = np.nan
df_rank_copy['Silver'] = np.nan
df_rank_copy['Bronze'] = np.nan
for n in range (0, len(df_rank_copy.index)):
    if df_rank_copy.loc[n, 'Medal'] == 'Gold':
        df_rank_copy.loc[n,'Gold'] = 1
    elif df_rank_copy.loc[n, 'Medal'] == 'Silver':
        df_rank_copy.loc[n,'Silver'] = 1
    else:
        df_rank_copy.loc[n,'Bronze'] = 1
df_rank_10 = df_rank_copy.groupby(['Country'], as_index=False)[['Gold','Silver','Bronze']].count()
df_rank_10.sort_values(by=['Gold','Silver','Bronze'], ascending=False, inplace=True)
df_rank_10 = df_rank_10.nlargest(10, 'Gold')
check_02_04(df_rank_10)
df_rank_10

          Country  Gold  Silver  Bronze
75  United States    44      32      25
58         Russia    26      21      16
24        Germany    20      18      27
13          China    16      22      12
22         France    15       7      15
33          Italy    13      10      12
3       Australia     9       9      23
16           Cuba     9       8       8
73        Ukraine     9       2      12
39   Korea, South     7      15       5

In [62]:
df_rank_10

          Country  Gold  Silver  Bronze
75  United States    44      32      25
58         Russia    26      21      16
24        Germany    20      18      27
13          China    16      22      12
22         France    15       7      15
33          Italy    13      10      12
3       Australia     9       9      23
16           Cuba     9       8       8
73        Ukraine     9       2      12
39   Korea, South     7      15       5

***

### 🎊 문제가 끝났습니다. 제출양식과 일정에 맞춰 제출해주시기를 바랍니다!

### 제출양식
- 이 파일은 EDA TEST 3회차 노트북입니다. 따라서 제출시 파일명은 아래와 같습니다.
- [DS]edalvtest_03_yourname.ipynb

***

# 문의사항 및 의견이 있는 경우 작성해주세요.