<div align="center">
    <img src="images/zb-logo.png" alt="제로베이스" width="100%">
    <br>
    <a href="https://zerobaseschool.notion.site/DS-EDA-Lv-Test-b7d5e895c7cd4dda813c8fe2f2c23f79"><img src="images/openinnotion_logo.png" alt="EDA Lv Test Doc" width="12%"></a>

이 Jupyter Notebook 파일은 <a href="https://zero-base.co.kr/category_data_camp/school_DS">제로베이스</a>에서 제공하는 **EDA Level Test** 문제입니다.<br>
지금까지 공부하신 내용으로 데이터 분석에 대해 좀 더 연습할 수 있는 시간이 되셨으면 좋겠습니다.🙂<br>
**EDA Level Test**에 대한 안내 사항은 상단 **Open in ZeroBase Notion** 로고를 클릭하여 확인해주세요!<br>
반드시 시작 전에 내용을 숙지해주시기를 바랍니다!<br>
</div>

***

<h1 style="background-color:#9F81F7;color:#D8D8D8;font-weight:bold;display:inline-block;padding: 5px">EDA Level Test 04 ⭐️⭐️</h1>

| Week | Data Analysis | Difficulty | This Notebook |
|------|---------------|------------|-------|
| 1    | 서울시 인구 데이터 | ⭐️ ||
| 2    | 화장품 성분 데이터 | ⭐️⭐️⭐️ ||
| 3    | 올림픽 데이터 | ⭐️⭐️ ||
| 4    | 국가별 인터넷 사용률 데이터 |⭐️⭐️ |👈|
| 5    | 전국 박물관/미술관 정보 표준 데이터 | ⭐️⭐️⭐️ ||
| 6    | 서울시 흡연율 통계 데이터 | ⭐️⭐️ ||
| 7    | 웹크롤링 | ⭐️ ||
| 8    | 서울시 지하철 호선별 역별 유/무임 승하차 인원 정보 데이터 | ⭐️⭐️ ||
| 9    | 서울시 교통사고 현황 (사고유형별) 통계 데이터 | ⭐️⭐️ ||
| 10   | 서울시 교통사고 현황 (사고유형별) 통계 + 서울시 차량통행속도 (구별/월별) 통계 + 서울시 인구밀도 (구별) 통계 | ⭐️⭐️⭐️ ||

## 문제 소개 및 데이터 준비 단계

### Data 원본 출처

### Target Data(CSV): Global Internet Usage(국가별 인터넷 사용률)
- Source: [Kaggle](https://www.kaggle.com/datasets/sansuthi/gapminder-internet)
- DownLoad: [archive.zip](https://www.kaggle.com/datasets/sansuthi/gapminder-internet/download)

### Reference Data01(HTML Link): 국가별 인구(Population) Data
- Source: [Wiki](https://en.wikipedia.org/wiki/List_of_countries_and_dependencies_by_population)

### Reference Data02(CSV): 국가별 ISO코드 / 지역 분류(Region) Data
- Source: [Kaggle](https://www.kaggle.com/datasets/andradaolteanu/country-mapping-iso-continent-region)
- DownLoad: [archive.zip](https://www.kaggle.com/datasets/andradaolteanu/country-mapping-iso-continent-region/download)


### 참고사항
- 위 3개의 Data들은 생성 시기가 다르므로 이 Test에서 도출되는 결과는 실제와 일치하지 않습니다.
<br></br>
- 문제에 hint가 있을 경우, 해당 hint를 이용하지 않으셔도 무방합니다.
<br></br>
- 해당 Test는 Wiki의 Online Data를 가져오는 내용을 포함하고 있습니다.
    - 해당 내용이 변경될 경우 추후 공유될 정답과 다를 수 있습니다.
    - 문제 제작시의 Data는 추후 공유될 정답과 함께 제공합니다. 해당 Data는 아래의 경로에 있습니다.  
        - 국가별 인구 Data  
            <code> [DS]EDA Level Test_week 4/solution/datas/wiki_population.csv </code>  
<br></br>
- 해당 Test는 pycountry 라는 Library를 사용할 예정입니다.
    - https://pypi.org/project/pycountry/#description
    - https://github.com/flyingcircusio/pycountry
<br></br>
    - 해당 Library가 없는 경우 아래 명령어를 사용하여 설치하시기 바랍니다.  
    <code> pip install pycountry </code> 또는 <code> conda install -c conda-forge pycountry </code>

In [1]:
# 설치 필수
# !pip install pycountry
# !pip install lxml

In [2]:
import pandas as pd
import numpy as np
# 채점을 위한 코드입니다. 반드시 실행해주세요.
from grading import *

df_target = pd.read_csv('./datas/gapminder_internet.csv')
df_target

                country  incomeperperson  internetuserate  urbanrate
0           Afghanistan              NaN         3.654122      24.04
1               Albania      1914.996551        44.989947      46.72
2               Algeria      2231.993335        12.500073      65.22
3               Andorra     21943.339900        81.000000      88.92
4                Angola      1381.004268         9.999954      56.70
..                  ...              ...              ...        ...
208             Vietnam       722.807559        27.851822      27.84
209  West Bank and Gaza              NaN        36.422772      71.90
210         Yemen, Rep.       610.357367        12.349750      30.64
211              Zambia       432.226337        10.124986      35.42
212            Zimbabwe       320.771890        11.500415      37.34

[213 rows x 4 columns]

## 문제 시작! 🏃🏻

## 1단계: Target Data 불러오기 & 전처리
***

### 문제 1-1) Target Data 전처리 01 (5점)
- 위에서 읽은 DataFrame에서 Null값을 처리하고자 합니다. 아래 조건에 맞게 Null값을 처리하세요.
<br></br>
    - 조건1: 'incomeperperson', 'internetuserate', 'urbanrate' Column(열)에 하나라도 Null값이 있다면 그 row(행)를 삭제(drop)하세요.
    - 조건2: Index와 순서(order)는 변경하지 마세요.
<br></br>
- 완료 후 결과 dataframe 변수를 check_01_01 함수에 입력하여 채점하세요.

In [3]:
# 1-1
df_target = df_target.dropna()
check_01_01(df_target)

정답입니다! 5점 누적 되었습니다!
현재 누적 점수: 5 / 100

In [4]:
df_target

                 country  incomeperperson  internetuserate  urbanrate
1                Albania      1914.996551        44.989947      46.72
2                Algeria      2231.993335        12.500073      65.22
3                Andorra     21943.339900        81.000000      88.92
4                 Angola      1381.004268         9.999954      56.70
5    Antigua and Barbuda     11894.464070        80.645455      30.46
..                   ...              ...              ...        ...
207            Venezuela      5528.363114        35.850437      93.32
208              Vietnam       722.807559        27.851822      27.84
210          Yemen, Rep.       610.357367        12.349750      30.64
211               Zambia       432.226337        10.124986      35.42
212             Zimbabwe       320.771890        11.500415      37.34

[182 rows x 4 columns]

### 문제 1-2) Target Data 전처리 02 (5점)
- 1-1의 DataFrame(df_target)과 아래의 df_target_change_list를 이용하여 아래 조건에 맞게 국가명(컬럼명: 'country')을 변경하세요.
<br></br>
    - 참고: 국가명을 변경하는 이유는 추후(문제 2-4) pycountry Library를 사용하여 국가코드(ex: 대한민국-KR)를 얻기 위함입니다.
<br></br>
    - 아래 df_target_change_list는 변경 대상인 df_target의 index와 그에 맞는 국가명이 쌍(tuple)들을 값으로 가지고 있습니다.
<br></br>
        - 조건1: df_target_change_list를 이용하여 df_target의 국가명을 변경하세요.
        - 조건2: Index 또는 순서(order)는 변경하지 마세요.
<br></br>
- 완료 후 결과 dataframe 변수를 check_01_02 함수에 입력하여 채점하세요.

In [5]:
df_target_change_list = [
    (33, 'Cabo Verde'),
    (35, 'Central African Republic'),
    (41, 'Congo, The Democratic Republic of the'),
    (42, 'Congo'),
    (45, "Côte d'Ivoire"),
    (49, 'Czech Republic'),
    (53, 'Dominican Republic'),
    (83, 'Hong Kong'),
    (100, 'Korea, Republic of'),
    (103, "Lao People's Democratic Republic"),
    (112, 'Macao'),
    (113, 'Republic of North Macedonia'),
    (125, 'Federated States of Micronesia'),
    (183, 'Eswatini'),
    (210, 'Yemen')
]

In [6]:
# 1-2
for i, v in dict(df_target_change_list).items():
    df_target = df_target.replace(df_target.loc[i, : ]['country'], v)
check_01_02(df_target)

정답입니다! 5점 누적 되었습니다!
현재 누적 점수: 10 / 100

### 문제 1-3) Target Data 전처리 03 (10점)
- 1-2의 DataFrame(df_target)과 pycountry Library를 이용하여 아래 조건에 맞게 국가코드를 구하세요.
<br></br>
    - 참고: **pycountry.countries**
<br></br>
        - ISO 3166-2(전 세계 나라 및 부속 영토의 주요 구성 단위의 명칭에 고유 부호(코드)를 부여하는 국제 표준) 기준 국가별 코드를 얻을 수 있는 Python Library
<br></br>
        - 국가명 표기 방식에 따라 잘못된 값 또는 값 검색이 안되는 경우가 많아 주의가 필요함
<br></br>
            - 예시: 대한민국의 경우 'south korea', 'republic of korea', 'korea', 'korea, republic of' 등으로 표기되는데, 이 중 'korea, republic of' 로만 정확한 국가 코드를 얻을 수 있음
            - 혼선을 줄이기 위하여 문제 1-2와 같이 변경할 국가명을 제공함
<br></br>
        - 사용법(상세 사용법은 2.Datas의 참고사항 내 링크 참조)
<br></br>
            - 국가 검색 방법
<br></br>
                - 일반 검색: pycountry.countries.get(name=country_name) -> 하나의 결과값을 return
                - fuzzy 검색: pycountry.countries.search_fuzzy(country_name) -> 하나 이상의 결과값을 list형태로 return
<br></br>
            - 예시
<br></br>
            <img src="images/04-1-3-001.png" style="margin:auto" width=500/>
<br></br>
            <img src="images/04-1-3-002.png" style="margin:auto" width=600/>
<br></br>
    - 조건1: df_target에 'code'컬럼을 추가하여 각 row(행)의 국가명에 맞는 2글자 국가코드(alpha_2)를 입력하세요.
<br></br>
    - 조건2: 일반검색(pycountry.countries.get(name=country_name))을 우선 이용 해보고, 결과값이 안 나올 경우 fuzzy 검색(pycountry.countries.search_fuzzy(country_name))을 활용하여 검색하세요.
<br></br>
    - 조건3: fuzzy 검색을 이용할 경우, 결과값 list의 첫번째 값(index=0)의 국가코드를 입력하세요.
<br></br>
    - 조건4: Index 또는 순서(order)는 변경하지 마세요.
<br></br>
<br></br>
    - hint: Python 예외처리(try-except)를 활용해 보세요.
<br></br>
<br></br>
- 완료 후 결과 dataframe 변수를 check_01_03 함수에 입력하여 채점하세요.

In [7]:
df_target.head()

               country  incomeperperson  internetuserate  urbanrate
1              Albania      1914.996551        44.989947      46.72
2              Algeria      2231.993335        12.500073      65.22
3              Andorra     21943.339900        81.000000      88.92
4               Angola      1381.004268         9.999954      56.70
5  Antigua and Barbuda     11894.464070        80.645455      30.46

In [8]:
# 1-3
import pycountry

df_target['code'] = 1
for i in df_target['country']:
    try:
        country_name = i
        country = pycountry.countries.get(name=country_name)
        if country == None:
            df_target.loc[df_target['country']==i,'code'] = np.nan
        else:
            df_target.loc[df_target['country']==i,'code'] = country.alpha_2
        
    except:
        country_name = i
        country = pycountry.countries.search_fuzzy(country_name)
        df_target.loc[df_target['country']==i,'code'] = country[0].alpha_2
check_01_03(df_target)

정답입니다! 10점 누적 되었습니다!
현재 누적 점수: 20 / 100

In [9]:
df_target

                 country  incomeperperson  internetuserate  urbanrate code
1                Albania      1914.996551        44.989947      46.72   AL
2                Algeria      2231.993335        12.500073      65.22   DZ
3                Andorra     21943.339900        81.000000      88.92   AD
4                 Angola      1381.004268         9.999954      56.70   AO
5    Antigua and Barbuda     11894.464070        80.645455      30.46   AG
..                   ...              ...              ...        ...  ...
207            Venezuela      5528.363114        35.850437      93.32  NaN
208              Vietnam       722.807559        27.851822      27.84  NaN
210                Yemen       610.357367        12.349750      30.64   YE
211               Zambia       432.226337        10.124986      35.42   ZM
212             Zimbabwe       320.771890        11.500415      37.34   ZW

[182 rows x 5 columns]

## 2단계: Reference Data01: 불러오기 & 전처리 & 합치기
***

### 문제 2-1) Web Data 가져오기 (10점)
- 아래 제시된 Link에 있는 국가별 인구에 대한 Table을 아래 조건에 맞게 예시와 같이 Pandas DataFrame으로 불러오세요.
<br></br>
    - Link: https://en.wikipedia.org/wiki/List_of_countries_and_dependencies_by_population
<br></br>
    <img src="images/04-2-1-001.png" style="margin:auto" width=400/>
<br></br>
    - 예시
<br></br>
    <img src="images/04-2-1-002.png" style="margin:auto" width=600/>
<br></br>
    - 조건: 해당 DataFrame의 변수명을 'df_population'으로 지정해주세요.
<br></br>
<br></br>
    - hint: pandas의 기능 중에 웹페이지의 Table들을 읽어와 DataFrame으로 만들어주는 method가 있습니다.
<br></br>
<br></br>
- 완료 후 결과 dataframe 변수를 check_02_01 함수에 입력하여 채점하세요.

In [10]:
path = 'https://en.wikipedia.org/wiki/List_of_countries_and_dependencies_by_population'
df_population = pd.read_html(path)
df_population = df_population[0].drop(['Unnamed: 0','Unnamed: 6'], axis=1)
df_population = df_population.rename(columns={'Location':'Country / Dependency'})
df_population
check_02_01(df_population)

정답입니다! 10점 누적 되었습니다!
현재 누적 점수: 30 / 100

In [11]:
df_population

,Country / Dependency,Population,% of world,Date,Source (official or from the United Nations)
0,World,8093481000,100%,7 Mar 2024,UN projection[3]
1,China,1409670000,NaN,31 Dec 2023,Official estimate[5]
2,India,1392329000,NaN,1 Jul 2023,Official projection[6]
3,United States,335893238,NaN,1 Jan 2024,Official estimate[7]
4,Indonesia,279118866,NaN,1 Jul 2023,National annual projection[8]
...,...,...,...,...,...
236,Niue,1689,NaN,11 Nov 2022,2022 Census [232]
237,Tokelau (NZ),1647,NaN,1 Jan 2019,2019 Census [233]
238,Vatican City,764,NaN,26 Jun 2023,Official figure[234]
239,Cocos (Keeling) Islands (Australia),593,NaN,30 Jun 2020,2021 Census[235]
240,Pitcairn Islands (UK),47,NaN,1 Jul 2021,Official estimate[236]

### 문제 2-2) Population Data 전처리 01 (5점)
- 2-1의 DataFrame(df_population)을 아래의 조건에 맞게 변경하세요.
<br></br>
    - 조건1: Column(열) 중 'Country / Dependency', 'Population' 2개만 남기세요.
    - 조건2: 컬럼명을 아래와 같이 변경하세요.
        - 'Country / Dependency' -> 'country'
        - 'Population' -> 'population'
    - 조건3: 'country' Column(열)의 값이  'World'인 첫번째 인덱스(index=0)을 삭제하세요.
    - 조건4: Index 또는 순서(order)는 변경하지 마세요.
<br></br>
- 완료 후 결과 dataframe 변수를 check_02_02 함수에 입력하여 채점하세요.

In [12]:
# 2-2
df_population.drop(['% of world','Date','Source (official or from the United Nations)'], axis=1, inplace=True)
df_population.rename(columns={
    'Country / Dependency':'country',
    'Population':'population'},inplace=True)
df_population.drop([0],axis=0,inplace=True)
df_population.head()
check_02_02(df_population)

정답입니다! 5점 누적 되었습니다!
현재 누적 점수: 35 / 100

In [13]:
df_population

                                 country  population
1                                  China  1409670000
2                                  India  1392329000
3                          United States   335893238
4                              Indonesia   279118866
5                               Pakistan   241499431
..                                   ...         ...
236                                 Niue        1689
237                         Tokelau (NZ)        1647
238                         Vatican City         764
239  Cocos (Keeling) Islands (Australia)         593
240                Pitcairn Islands (UK)          47

[240 rows x 2 columns]

### 문제 2-3) Population Data 전처리 02 (5점)
- 2-2의 DataFrame(df_population)과 아래의 df_population_change_dict를 이용하여 아래 조건에 맞게 국가명(컬럼명: 'country')을 변경하세요.
<br></br>
    - 참고: 국가명을 변경하는 이유는 추후 문제에서 1단계에서 만들었던 df_target과 합치기 위함입니다.
        - 변경 국가는 1단계의 df_target에 있는 국가만 해당됩니다.
        - 일부 국가명의 표현이 다르기 때문에 df_target을 기준으로 표기를 통일합니다.
<br></br>
    - 아래 df_population_change_dict는 변경 대상인 df_population의 기존 국가명과 변경할 국가명이 key-value로 이루어져 있습니다.
<br></br>
        - 조건1: df_population_change_dict를 이용하여 df_population의 국가명을 변경하세요.
        - 조건2: Index 또는 순서(order)는 변경하지 마세요.
<br></br>
- 완료 후 결과 dataframe 변수를 check_02_03 함수에 입력하여 채점하세요.

In [14]:
df_population_change_dict = {
    'Bermuda (United Kingdom)': 'Bermuda',
    'Cape Verde': 'Cabo Verde',
    'DR Congo': 'Congo, The Democratic Republic of the',
    'Ivory Coast': "Côte d'Ivoire",
    'Greenland (Denmark)': 'Greenland',
    'Hong Kong (China)': 'Hong Kong',
    'South Korea': 'Korea, Republic of',
    'Laos': "Lao People's Democratic Republic",
    'Macau (China)': 'Macao',
    'North Macedonia': 'Republic of North Macedonia',
    'Micronesia': 'Federated States of Micronesia',
    'Puerto Rico (United States)': 'Puerto Rico',
    'Slovakia': 'Slovak Republic',
    'East Timor': 'Timor-Leste',
}

In [15]:
# 2-3
df_population['country'] = df_population['country'].replace(df_population_change_dict)
check_02_03(df_population)

정답입니다! 5점 누적 되었습니다!
현재 누적 점수: 40 / 100

In [16]:
df_population

                                 country  population
1                                  China  1409670000
2                                  India  1392329000
3                          United States   335893238
4                              Indonesia   279118866
5                               Pakistan   241499431
..                                   ...         ...
236                                 Niue        1689
237                         Tokelau (NZ)        1647
238                         Vatican City         764
239  Cocos (Keeling) Islands (Australia)         593
240                Pitcairn Islands (UK)          47

[240 rows x 2 columns]

### 문제 2-4) Data 합치기(10점)
- 1단계의 DataFrame(df_target)과 2-3의 DataFrame(df_population)을 아래의 조건에 맞게 합치세요.
<br></br>
    - df_target에 df_population의 Data를 추가하려 합니다.
<br></br>
        - 조건1: df_target, df_population의 국가명('country' Column(열)의 value)이 같은 Data끼리 합쳐주세요.
<br></br>
        - 조건2: 결합 방식은 교집합(겹치는 국가명이 있는 경우만 추출)으로 지정해 주세요.
<br></br>
        - 조건3: Column(열)방향으로 DataFrame을 합쳐주세요.
<br></br>
        - 조건4: 'code' Column(열)을 기준으로 오름차순으로 정렬해주세요.
<br></br>
        - 조건5: index를 reset해주세요.
<br></br>
        - 조건6: 결과 DataFrame의 Column은 6개('country', 'incomeperperson', 'internetuserate', 'urbanrate', 'code', 'population')이어야 합니다.
<br></br>
        - 조건7: 결과 DataFrame의 변수는 'df' 로 지정해 주세요.
<br></br>
<br></br>
        - hint1: 조건1 -> key='country' 또는 on='country'
<br></br>
        - hint2: 조건2 -> join='inner' 또는 how='inner'(DataFrame 순서에 따라 'left', 'right'도 가능)
<br></br>
<br></br>
- 완료 후 결과 dataframe 변수를 check_02_04 함수에 입력하여 채점하세요.

In [17]:
df_target.head()

               country  incomeperperson  internetuserate  urbanrate code
1              Albania      1914.996551        44.989947      46.72   AL
2              Algeria      2231.993335        12.500073      65.22   DZ
3              Andorra     21943.339900        81.000000      88.92   AD
4               Angola      1381.004268         9.999954      56.70   AO
5  Antigua and Barbuda     11894.464070        80.645455      30.46   AG

In [18]:
# 2-4
df = pd.merge(df_target, df_population, how='inner', on='country').sort_values(by='code', ascending=True, axis=0).reset_index(drop=True)
check_02_04(df)

오답입니다. 다시 한번 확인해주세요.
현재 누적 점수: 40 / 100

In [19]:
df

,country,incomeperperson,internetuserate,urbanrate,code,population
0,Andorra,21943.339900,81.000000,88.92,AD,85101
1,United Arab Emirates,21087.394120,77.996781,77.88,AE,9282410
2,Antigua and Barbuda,11894.464070,80.645455,30.46,AG,100772
3,Albania,1914.996551,44.989947,46.72,AL,2761785
4,Armenia,1326.741757,44.001025,63.86,AM,2981200
...,...,...,...,...,...,...
173,Syria,1525.780116,20.663156,54.22,NaN,22923000
174,Tanzania,456.385712,11.000055,25.52,NaN,61741120
175,Turkey,5348.597192,39.820178,68.68,NaN,85372377
176,Venezuela,5528.363114,35.850437,93.32,NaN,28302000
177,Vietnam,722.807559,27.851822,27.84,NaN,100300000

## 3단계: Reference Data02: 불러오기 & 전처리 & 합치기
***

In [20]:
df_region = pd.read_csv('./datas/continents2.csv')
df_region

,name,alpha-2,alpha-3,country-code,iso_3166-2,region,sub-region,intermediate-region,region-code,sub-region-code,intermediate-region-code
0,Afghanistan,AF,AFG,4,ISO 3166-2:AF,Asia,Southern Asia,NaN,142.0,34.0,NaN
1,Åland Islands,AX,ALA,248,ISO 3166-2:AX,Europe,Northern Europe,NaN,150.0,154.0,NaN
2,Albania,AL,ALB,8,ISO 3166-2:AL,Europe,Southern Europe,NaN,150.0,39.0,NaN
3,Algeria,DZ,DZA,12,ISO 3166-2:DZ,Africa,Northern Africa,NaN,2.0,15.0,NaN
4,American Samoa,AS,ASM,16,ISO 3166-2:AS,Oceania,Polynesia,NaN,9.0,61.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...
244,Wallis and Futuna,WF,WLF,876,ISO 3166-2:WF,Oceania,Polynesia,NaN,9.0,61.0,NaN
245,Western Sahara,EH,ESH,732,ISO 3166-2:EH,Africa,Northern Africa,NaN,2.0,15.0,NaN
246,Yemen,YE,YEM,887,ISO 3166-2:YE,Asia,Western Asia,NaN,142.0,145.0,NaN
247,Zambia,ZM,ZMB,894,ISO 3166-2:ZM,Africa,Sub-Saharan Africa,Eastern Africa,2.0,202.0,14.0
248,Zimbabwe,ZW,ZWE,716,ISO 3166-2:ZW,Africa,Sub-Saharan Africa,Eastern Africa,2.0,202.0,14.0

### 문제 3-1) Region Data 전처리 01 (10점)
- 위의 DataFrame(df_region)을 아래의 조건에 맞게 변경하세요.
<br></br>
    - 조건1
        - 특정 국가('Namibia')의 국가코드가 'NA'이기 때문에 위와 같이 DataFrame을 불러올경우 해당 국가코드가 NaN값으로 처리됩니다.
        - 해당 국가의 국가코드를 'NA'로 변경하세요.(해당 값의 type이 string이어야 합니다.)
        - 참고
            - 아래 조건3에 따른 Column(열)명을 변경하기 전에는 'alpha-2', 변경 후에는 'code' Column(열)에 국가코드가 있습니다.
            - 국가명 Column(열)명은 'name'입니다.
<br></br>
    - 조건2
        - 아래 df_region_drop_col은 Data 분석시 필요 없는 Column(열)입니다.
        - df_region_drop_col을 참고하여 df_region의 Column(열)들을 삭제(drop)하세요.
<br></br>
    - 조건3
        - 아래 df_region_rename_dict는 기존 컬럼명 - 변경할 컬럼명이 key-value로 이루어져 있습니다.
        - df_region_rename_dict를 참고하여 df_region의 Column(열)명을 변경하세요.
<br></br>
    - 조건4: Index 또는 순서(order)는 변경하지 마세요.
<br></br>
- 완료 후 결과 dataframe 변수를 check_03_02 함수에 입력하여 채점하세요.

In [21]:
df_region_drop_col = [
                    'country-code',
                    'alpha-3',
                    'iso_3166-2',
                    'region-code',
                    'sub-region-code',
                    'intermediate-region-code'
                    ]

df_region_rename_dict = {
                        'alpha-2': 'code',
                        'sub-region': 'sub_region',
                        'intermediate-region': 'intermediate_region',
                        }

In [22]:
# 3-1
df_region.loc[df_region['name']=='Namibia','alpha-2'] = 'NA'
df_region.drop(df_region_drop_col, axis=1, inplace=True)
df_region.rename(columns=df_region_rename_dict, inplace=True)
check_03_01(df_region)

정답입니다! 10점 누적 되었습니다!
현재 누적 점수: 50 / 100

In [23]:
df_region

                  name code   region          sub_region intermediate_region
0          Afghanistan   AF     Asia       Southern Asia                 NaN
1        Åland Islands   AX   Europe     Northern Europe                 NaN
2              Albania   AL   Europe     Southern Europe                 NaN
3              Algeria   DZ   Africa     Northern Africa                 NaN
4       American Samoa   AS  Oceania           Polynesia                 NaN
..                 ...  ...      ...                 ...                 ...
244  Wallis and Futuna   WF  Oceania           Polynesia                 NaN
245     Western Sahara   EH   Africa     Northern Africa                 NaN
246              Yemen   YE     Asia        Western Asia                 NaN
247             Zambia   ZM   Africa  Sub-Saharan Africa      Eastern Africa
248           Zimbabwe   ZW   Africa  Sub-Saharan Africa      Eastern Africa

[249 rows x 5 columns]

### 문제 3-2) Data 합치기(10점)
- 2단계의 DataFrame(df)과 3-1의 DataFrame(df_region)을 아래의 조건에 맞게 합치세요.
<br></br>
    - df에 df_region의 Data를 추가하려 합니다.
<br></br>
        - 조건1: df, df_region 국가코드('code' Column(열)의 value)가 같은 Data끼리 합쳐주세요.
<br></br>
        - 조건2: 결합 방식은 교집합(겹치는 국가코드가 있는 경우만 추출)으로 지정해 주세요.
<br></br>
        - 조건3: Column(열)방향으로 DataFrame을 합쳐주세요.
<br></br>
        - 조건4: 'code' Column(열)을 기준으로 오름차순으로 정렬해주세요.
<br></br>
        - 조건5
            - 아래 df_rename_dict는 기존 컬럼명 - 변경할 컬럼명이 key-value로 이루어져 있습니다.
            - df_rename_dict를 참고하여 df의 Column(열)명을 변경하세요.
<br></br>
        - 조건6
            - 아래 new_col_order는 변경하고자하는 Column(열)의 순서대로 Column(열)명을 값으로 가지고 있습니다.
            - new_col_order를 참고하여 df의 Column(열)의 순서를 변경하세요.
<br></br>
        - 조건7: 'name' Column(열)은 삭제(drop)해 주세요
<br></br>
        - 조건8: index를 reset해주세요.
<br></br>
        - 조건9: 결과 DataFrame의 Column은 6개('country', 'incomeperperson', 'internetuserate', 'urbanrate', 'code', 'population')이어야 합니다.
<br></br>
        - 조건10: 결과 DataFrame의 변수는 'df' 로 지정해 주세요.
<br></br>
<br></br>
        - hint1: 조건1 -> key='code' 또는 on='code'
<br></br>
        - hint2: 조건2 -> join='inner' 또는 how='inner'(DataFrame 순서에 따라 'left', 'right'도 가능)
<br></br>
<br></br>
- 완료 후 결과 dataframe 변수를 check_03_02 함수에 입력하여 채점하세요.

In [24]:
df_rename_dict = {
                'incomeperperson': 'income_per_person',
                'internetuserate': 'internet_use_rate',
                }

df_drop_col = ['name']

new_col_order = [
                'code',
                'country',
                'population',
                'income_per_person',
                'internet_use_rate',
                'urbanrate',
                'region',
                'sub_region',
                'intermediate_region'
                ]

In [25]:
# 3-2
# 참고: 'name' Column(열)은 new_col_order 순서로 맞출 때 사라짐.

df_merge = pd.merge(df, df_region, how='inner', on='code').sort_values(by='code')
df_merge = df_merge.rename(columns=df_rename_dict)
df_merge = df_merge[new_col_order].reset_index(drop=True)
df = df_merge.copy()
df

,code,country,population,income_per_person,internet_use_rate,urbanrate,region,sub_region,intermediate_region
0,AD,Andorra,85101,21943.339900,81.000000,88.92,Europe,Southern Europe,NaN
1,AE,United Arab Emirates,9282410,21087.394120,77.996781,77.88,Asia,Western Asia,NaN
2,AG,Antigua and Barbuda,100772,11894.464070,80.645455,30.46,Americas,Latin America and the Caribbean,Caribbean
3,AL,Albania,2761785,1914.996551,44.989947,46.72,Europe,Southern Europe,NaN
4,AM,Armenia,2981200,1326.741757,44.001025,63.86,Asia,Western Asia,NaN
...,...,...,...,...,...,...,...,...,...
159,WS,Samoa,205557,1784.071284,6.965038,23.00,Oceania,Polynesia,NaN
160,YE,Yemen,31888698,610.357367,12.349750,30.64,Asia,Western Asia,NaN
161,ZA,South Africa,62027503,3745.649852,12.334893,60.74,Africa,Sub-Saharan Africa,Southern Africa
162,ZM,Zambia,19610769,432.226337,10.124986,35.42,Africa,Sub-Saharan Africa,Eastern Africa
163,ZW,Zimbabwe,15178979,320.771890,11.500415,37.34,Africa,Sub-Saharan Africa,Eastern Africa

In [26]:
check_03_02(df)

정답입니다! 10점 누적 되었습니다!
현재 누적 점수: 60 / 100

In [49]:
df

,code,country,population,income_per_person,internet_use_rate,urbanrate,region,sub_region,intermediate_region,weighted_ave_internet,weighted_ave_income
0,AD,Andorra,85101,21943.339900,81.000000,88.92,Europe,Southern Europe,-,0,0
1,AE,United Arab Emirates,9282410,21087.394120,77.996781,77.88,Asia,Western Asia,-,0,0
2,AG,Antigua and Barbuda,100772,11894.464070,80.645455,30.46,Americas,Latin America and the Caribbean,Caribbean,0,0
3,AL,Albania,2761785,1914.996551,44.989947,46.72,Europe,Southern Europe,-,0,0
4,AM,Armenia,2981200,1326.741757,44.001025,63.86,Asia,Western Asia,-,0,0
...,...,...,...,...,...,...,...,...,...,...,...
159,WS,Samoa,205557,1784.071284,6.965038,23.00,Oceania,Polynesia,-,0,0
160,YE,Yemen,31888698,610.357367,12.349750,30.64,Asia,Western Asia,-,0,0
161,ZA,South Africa,62027503,3745.649852,12.334893,60.74,Africa,Sub-Saharan Africa,Southern Africa,0,0
162,ZM,Zambia,19610769,432.226337,10.124986,35.42,Africa,Sub-Saharan Africa,Eastern Africa,0,0
163,ZW,Zimbabwe,15178979,320.771890,11.500415,37.34,Africa,Sub-Saharan Africa,Eastern Africa,0,0

## 4단계: Data 분석하기(가중 평균 & 분산)
***

### 문제 4-1) 지역대륙별 가준 평균 구하기 (15점)
- 3단계 DataFrame(df)의 국가별 인터넷 사용률(internet_use_rate) 및 인당 소득(income_per_person)을 대륙(region) 또는 지역대륙(sub_region)별로 평균을 합산하여 보기 위해서는 단순 평균이 아닌 국가별 인구수(population)을 가중한 평균을 계산하여야 합니다.
<br></br>
- 3단계 DataFrame(df)을 이용하여 지역대륙(sub_region)별 조건에 맞게 가중평균을 구하세요.
<br></br>
- 참고
    - 가중 평균: 자료의 평균을 구할 때 자료 값의 중요도나 영향 정도에 해당하는 가중치를 반영하여 구한 평균값
<br></br>
    <img src="images/04-4-1-001.png" style="margin:auto" width=300/>
<br></br>
<br></br>
    - 조건1: 가중치(weights)는 population Column(열)을 이용하세요.
<br></br>
    - 조건2: 지역대륙(sub_region)의 인터넷 사용률(internet_use_rate) 및 인당 소득(income_per_person)을 아래 표와 같은 index, column 형태로 나타내주세요.
        - index = ['region', 'sub_region']
        - column = ['weighted_ave_internet', 'weighted_ave_income']
<br></br>
        <img src="images/04-4-1-002.png" style="margin:auto" width=400/>
<br></br>
    - 조건3: 결과 DataFrame의 변수는 'df_result' 로 지정해 주세요.
<br></br>
<br></br>
    - hint1: pandas.DataFrame.groupby
<br></br>
    - hint2: numpy.average
<br></br>
<br></br>
- 완료 후 결과 dataframe 변수를 check_04_01 함수에 입력하여 채점하세요.

In [50]:
df.head()

,code,country,population,income_per_person,internet_use_rate,urbanrate,region,sub_region,intermediate_region,weighted_ave_internet,weighted_ave_income
0,AD,Andorra,85101,21943.339900,81.000000,88.92,Europe,Southern Europe,-,0,0
1,AE,United Arab Emirates,9282410,21087.394120,77.996781,77.88,Asia,Western Asia,-,0,0
2,AG,Antigua and Barbuda,100772,11894.464070,80.645455,30.46,Americas,Latin America and the Caribbean,Caribbean,0,0
3,AL,Albania,2761785,1914.996551,44.989947,46.72,Europe,Southern Europe,-,0,0
4,AM,Armenia,2981200,1326.741757,44.001025,63.86,Asia,Western Asia,-,0,0

In [65]:
# 4-1
#가중 평균 함수 정의
df_group = df.groupby(['region','sub_region'])
weighted_avg_func_internet = lambda g:np.average(g['internet_use_rate'], weights=g['population'])
weighted_avg_func_income = lambda g:np.average(g['income_per_person'], weights=g['population'])

# #df_result에 가중 평균 컬럼 생성 후, 함수 적용
df['weighted_ave_internet'] = 0
df['weighted_ave_income'] = 0
df_result = df[['region','sub_region','weighted_ave_internet','weighted_ave_income']].groupby(['region','sub_region']).sum()
df_result['weighted_ave_internet'] = df_group.apply(weighted_avg_func_internet)
df_result['weighted_ave_income'] = df_group.apply(weighted_avg_func_income)
df_result
check_04_01(df_result)

정답입니다! 15점 누적 되었습니다!
현재 누적 점수: 75 / 100

In [59]:
df_result

                                          weighted_ave_internet  \
region   sub_region
Africa   Northern Africa                              27.740373
         Sub-Saharan Africa                           12.216930
Americas Latin America and the Caribbean              33.983626
         Northern America                             75.009337
Asia     Central Asia                                 20.420711
         Eastern Asia                                 39.426861
         South-eastern Asia                           17.902182
         Southern Asia                                 8.426790
         Western Asia                                 30.334335
Europe   Eastern Europe                               50.295189
         Northern Europe                              84.376600
         Southern Europe                              56.628011
         Western Europe                               80.596817
Oceania  Australia and New Zealand                    77.082606
         Melanesia                                     2.509922
         Micronesia                                    8.959140
         Polynesia                                     8.617012

                                          weighted_ave_income
region   sub_region
Africa   Northern Africa                          2276.241076
         Sub-Saharan Africa                        709.203575
Americas Latin America and the Caribbean          4948.872702
         Northern America                        36205.897008
Asia     Central Asia                             1293.514167
         Eastern Asia                             5904.244381
         South-eastern Asia                       1979.917963
         Southern Asia                             749.196873
         Western Asia                             6155.231284
Europe   Eastern Europe                           3636.977866
         Northern Europe                         27869.751219
         Southern Europe                         14937.792303
         Western Europe                          25256.167402
Oceania  Australia and New Zealand               23501.051504
         Melanesia                                 880.105518
         Micronesia                                760.262365
         Polynesia                                1863.107822

### 문제 4-2) 특정 조건의 가준 평균 구하기 (15점)
- 중국과 인도를 제외한 Eastern Asia, Southern Asia의 인터넷 사용률(internet_use_rate) 및 인당 소득(income_per_person)을 아래 조건에 맞게 구하세요.
<br></br>
- 참고: 4-1의 참고사항 참조
<br></br>
    - 조건1: 가중치(weights)는 population Column(열)을 이용하세요.
<br></br>
    - 조건2: 중국(국가코드(code): 'CN)과 인도(국가코드: 'IN')를 제외한 Asia(region) - Eastern Asia, Southern Asia  (sub_region)의 인터넷 사용률(internet_use_rate) 및 인당 소득(income_per_person)을 아래 표와 같은 index, column 형태로 나타내주세요.
        - index = ['region', 'sub_region']
        - column = ['weighted_ave_internet', 'weighted_ave_income']
<br></br>
        <img src="images/04-4-2-001.png" style="margin:auto" width=400/>
<br></br>
        <img src="images/04-4-2-002.png" style="margin:auto" width=400/>
<br></br>
    - 조건3: 결과 DataFrame의 변수는 'df_result' 로 지정해 주세요.
<br></br>
<br></br>
    - hint1: pandas.DataFrame.groupby
<br></br>
    - hint2: numpy.average
<br></br>
<br></br>
- 완료 후 결과 dataframe 변수를 check_04_02 함수에 입력하여 채점하세요.

In [74]:
#가중 평균 함수 정의
df_group = df.groupby(['region','sub_region'])
weighted_avg_func_internet = lambda g:np.average(g['internet_use_rate'], weights=g['population'])
weighted_avg_func_income = lambda g:np.average(g['income_per_person'], weights=g['population'])

# #df_result에 가중 평균 컬럼 생성 후, 함수 적용
df['weighted_ave_internet'] = 0
df['weighted_ave_income'] = 0
df_result = df[['region','sub_region','weighted_ave_internet','weighted_ave_income']].groupby(['region','sub_region']).sum()
df_result['weighted_ave_internet'] = df_group.apply(weighted_avg_func_internet)
df_result['weighted_ave_income'] = df_group.apply(weighted_avg_func_income)
df_result

In [79]:
# 4-2
df_asia = df[((df['code'] != 'CN') & (df['code'] != 'IN')) & #code가 CN과 IN이 아님
             ((df['sub_region'] == 'Eastern Asia') | (df['sub_region'] == 'Southern Asia'))] # region이 Eastern Asia거나 Southern Asia임
df_asia_group =df_asia.groupby(['region','sub_region'])

df_result = df_asia[['region','sub_region','weighted_ave_internet','weighted_ave_income']].groupby(['region','sub_region']).sum()
df_result['weighted_ave_internet'] = df_asia_group.apply(weighted_avg_func_internet)
df_result['weighted_ave_income'] = df_asia_group.apply(weighted_avg_func_income)
df_result

check_04_02(df_result)

정답입니다! 15점 누적 되었습니다!
현재 누적 점수: 90 / 100

In [80]:
df_result

                      weighted_ave_internet  weighted_ave_income
region sub_region
Asia   Eastern Asia               77.475066         32119.176145
       Southern Asia              11.209731           636.583657

***

### 🎊 문제가 끝났습니다. 제출양식과 일정에 맞춰 제출해주시기를 바랍니다!

### 제출양식
- 이 파일은 EDA Level TEST 4회차 노트북입니다. 따라서 제출시 파일명은 아래와 같습니다.
- [DS]edalvtest_04_yourname.ipynb

***

# 문의사항 및 의견이 있는 경우 작성해주세요.

In [34]:
# 2-4 에서 code를 '-'으로 처리하여 오류가 나는 것인지 궁금합니다.